input_video_path: "/mnt/d/Dataset/City/CityWay_part2.mp4"
output_video_path: "/mnt/d/Dataset/Output/detect_output.mp4"
model_path: "/home/wanglonglong/Learn_ROS2/03.my_robot/src/detect/model/best.onnx"
ignore_ratio: 0.25
